from enum import StrEnum


class ProposalStatus(StrEnum):
    ANALISE_CREDITO = "ANALISE_CREDITO"
    LAUDO = "LAUDO"
    JURIDICO = "JURIDICO"
    CONTRATO = "CONTRATO"
    REGISTRO = "REGISTRO"
    PAGAMENTO_VENDEDOR = "PAGAMENTO_VENDEDOR"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"


class HistoryAction(StrEnum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    STATUS_CHANGED = "STATUS_CHANGED"
